name: Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: "node:15"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build sources
        run: yarn build

      - name: Run tests
        run: yarn test
